# Generated by Django 2.2.4 on 2019-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stock_pcs', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('shop_id', models.CharField(max_length=255)),
                ('vip', models.BooleanField(default=False)),
            ],
        ),
    ]
